### ISSUE TITLE
python 3.4 installation fails on windows

### ISSUE THREAD

**Issue by monkut** [andialbrecht/sqlparse#182]
Got the following error trying to install into python 3.4 on windows (no issues installing into python 2.7):

running install
Traceback (most recent call last):
  File "setup.py", line 122, in <module>
    **kwargs
  File "C:\Python34\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 103, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
  File "C:\Python34\lib\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "C:\Python34\lib\site-packages\setuptools\command\easy_install.py", line 313, in finalize_options
    self.index_url, search_path=self.shadow_path, hosts=hosts,
  File "C:\Python34\lib\site-packages\setuptools\package_index.py", line 269, in __init__
    Environment.__init__(self,*args,**kw)
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 802, in __init__
    self.scan(search_path)
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 832, in scan
    self.add(dist)
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 852, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
TypeError: unorderable types: str() < NoneType()

**Comment by andialbrecht** [comment]
This sounds much like this issue https://github.com/pypa/pip/issues/2357

Could you make sure that setuptools is at least 14.3 and try again?

**Comment by asifm** [comment]
I was having the problem. I have setuptools 14.3.1, pip 6.0.8, Python 3.4.3 (all inside an Anaconda environment) in Windows 8.1

I solved it by changing lines 2395 and 2396 of the file
C:\Anaconda3\envs\py34\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py
```
self.py_version,
self.platform,
```
to
```
self.py_version or '',
self.platform or '',
```
I thought the issue was solved in a recent setuptools version. Not sure what's going on here.

**Comment by andialbrecht** [comment]
Closing this issue. It's a bug in the pip/setuptools stack and not related to sqlparse.
