### ISSUE TITLE
IndexError: list index out of range on version 0.1.18

### ISSUE THREAD

**Issue by benekastah** [andialbrecht/sqlparse#205]
I did:

```
sqlparse.parse(open('bad.sql').read())
```

And got this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chartdev/venv/local/lib/python2.7/site-packages/sqlparse/__init__.py", line 28, in parse
    return tuple(parsestream(sql, encoding))
  File "/home/chartdev/venv/local/lib/python2.7/site-packages/sqlparse/engine/__init__.py", line 55, in _group
    grouping.group(stmt)
  File "/home/chartdev/venv/local/lib/python2.7/site-packages/sqlparse/engine/grouping.py", line 461, in group
    func(tlist)
  File "/home/chartdev/venv/local/lib/python2.7/site-packages/sqlparse/engine/grouping.py", line 278, in group_identifier_list
    group = tlist.group_tokens(sql.IdentifierList, tokens)
  File "/home/chartdev/venv/local/lib/python2.7/site-packages/sqlparse/sql.py", line 375, in group_tokens
    idx = self.token_index(tokens[0])
IndexError: list index out of range
```

Here is the contents of bad.sql:

```
WITH latest AS (SELECT MAX(datestamp) AS date FROM some_table)
SELECT rank, geography, views,earnings, avg_n
FROM some_table_2 bi, latest
WHERE cms = {CMS}
  AND latest.date = bi.datestamp;
```

**Comment by benekastah** [comment]
This is also a problem on 0.2.0.dev0

**Comment by benekastah** [comment]
I should mention, this was not an issue in 0.1.15

**Comment by andialbrecht** [comment]
This was fixed in bd3ef1c (hotfix branch based on 0.1.18) and merged into master in 3360f5d.

**Comment by benekastah** [comment]
@andialbrecht That's awesome! Any idea when I can get that fix from pip?

**Comment by jmagnusson** [comment]
Would be awesome to have a new version with this!

**Comment by andialbrecht** [comment]
Sorry for the (looong) delay. Version 0.1.19 is out now.
