### ISSUE TITLE
Exception when parsing SELECT column AS

### ISSUE THREAD

**Issue by j-bennet** [andialbrecht/sqlparse#284]
Exception is thrown when parsing `SELECT column_name AS`:

```
$> bpython
bpython version 0.15 on top of Python 2.7.10 /Users/irina/.venvs/pgcli/bin/python
>>> from sqlparse import parse
>>> result = parse('select x as')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    result = parse('select x as')
  File "/Users/irina/.venvs/pgcli/lib/python2.7/site-packages/sqlparse/__init__.py", line 31, in parse
    return tuple(parsestream(sql, encoding))
  File "/Users/irina/.venvs/pgcli/lib/python2.7/site-packages/sqlparse/engine/filter_stack.py", line 36, in run
    stmt = grouping.group(stmt)
  File "/Users/irina/.venvs/pgcli/lib/python2.7/site-packages/sqlparse/engine/grouping.py", line 357, in group
    func(stmt)
  File "/Users/irina/.venvs/pgcli/lib/python2.7/site-packages/sqlparse/engine/grouping.py", line 129, in group_as
    _group(tlist, sql.Identifier, match, valid_prev, valid_next, post)
  File "/Users/irina/.venvs/pgcli/lib/python2.7/site-packages/sqlparse/engine/grouping.py", line 385, in _group
    grp = tlist.group_tokens(cls, from_idx, to_idx, extend=extend)
  File "/Users/irina/.venvs/pgcli/lib/python2.7/site-packages/sqlparse/sql.py", line 300, in group_tokens
    end_idx = end + include_end
TypeError: unsupported operand type(s) for +: 'NoneType' and 'bool'
```

**Comment by vmuriart** [comment]
hm... curious edge case. 
What version of sqlparse are you using?
in the example above, `as` is meant to be used as a keyword correct? ie, `as` itself is not the alias.

**Comment by j-bennet** [comment]
Version 0.2.0 and 0.2.1 both have this behavior.

`AS` was meant to be a keyword.

**Comment by vmuriart** [comment]
Whoops, sorry didn't mean to close the issue yet. I just pushed the changes.
Let us know if that doesn't fix the issue.

**Comment by andialbrecht** [comment]
I think we can close this issue. Tested it manually before and after the change and everything seems to work as expected, including the unittests ;)

Thanks for reporting and fixing this issue!
