### ISSUE TITLE
extract_table_names.py and Python 2.7

### ISSUE THREAD

**Issue by rchateauneu** [andialbrecht/sqlparse#290]
extract_table_names.py does not run, apparently, on Python 2.7:

C:\>python --version
Python 2.7.10

C:\>python extract_table_names.py
Traceback (most recent call last):
  File "extract_table_names.py", line 68, in <module>
    tables = ', '.join(extract_tables(sql))
  File "extract_table_names.py", line 59, in extract_tables
    return list(extract_table_identifiers(stream))
  File "extract_table_names.py", line 45, in extract_table_identifiers
    for item in token_stream:
  File "extract_table_names.py", line 33, in extract_from_part
    if is_subselect(item):
  File "extract_table_names.py", line 23, in is_subselect
    for item in parsed.tokens:
AttributeError: 'Token' object has no attribute 'tokens'

Thanks

**Comment by vmuriart** [comment]
Which version of sqlparse are you using?

The example file is broken though, we are still working on it

**Comment by rchateauneu** [comment]
Version 0.2.1. Another example which does not work for the moment:

"select col1 from tab1 where col2 in (select col3 from tab2)"

**Comment by rchateauneu** [comment]
Another example, which does notwork, is when subqueries are aliased:

"select alias1.cola from (select colb from tab1) alias1"

Thanks.

**Comment by vmuriart** [comment]
parsing doesnt work?
