### ISSUE TITLE
Error installing sqlparse (Permission denied)

### ISSUE THREAD

**Issue by arsari** [andialbrecht/sqlparse#318]
This is the message that I received when try to install the package:

arsari@ARSARIs-MacBook-Pro:~ $ pip install --upgrade sqlparse
Collecting sqlparse
  Using cached sqlparse-0.2.2-py2.py3-none-any.whl
Installing collected packages: sqlparse
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/sqlparse'
arsari@ARSARIs-MacBook-Pro:~ $

**Comment by vmuriart** [comment]
did you try running with elevated privileges or installing to user?

`sudo pip install --upgrade sqlparse`
or
`pip install --user --upgrade sqlparse`

**Comment by arsari** [comment]
@vmuriart I try with elevated privileges, as suggested,

_sudo pip install --upgrade sqlparse_

and install successfully...
