### ISSUE TITLE
IndexError if SELECT statement contains multiple user-defined variables

### ISSUE THREAD

**Issue by tsroten** [andialbrecht/sqlparse#358]
This only appears to happen when the semi-colon is on the end:
```
sqlparse.parse('SELECT @min_price:=MIN(price), @max_price:=MAX(price) FROM shop;')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/troten/code/sqlparse/sqlparse/__init__.py", line 31, in parse
    return tuple(parsestream(sql, encoding))
  File "/Users/troten/code/sqlparse/sqlparse/engine/filter_stack.py", line 36, in run
    stmt = grouping.group(stmt)
  File "/Users/troten/code/sqlparse/sqlparse/engine/grouping.py", line 357, in group
    func(stmt)
  File "/Users/troten/code/sqlparse/sqlparse/engine/grouping.py", line 146, in group_assignment
    _group(tlist, sql.Assignment, match, valid_prev, valid_next, post)
  File "/Users/troten/code/sqlparse/sqlparse/engine/grouping.py", line 385, in _group
    grp = tlist.group_tokens(cls, from_idx, to_idx, extend=extend)
  File "/Users/troten/code/sqlparse/sqlparse/sql.py", line 287, in group_tokens
    start = self.tokens[start_idx]
IndexError: list index out of range
```

This was reported by a user [in the mycli project](https://github.com/dbcli/mycli/issues/507).

This stack trace is from version `0.2.4.dev0`, running on Python 3.6 on macOS.

**Comment by andialbrecht** [comment]
Closing as dup of #359. Thanks for reporting @tsroten !
