### ISSUE TITLE
Reindent align sql ending with ";\n" causes IndexError

### ISSUE THREAD

**Issue by sparklxb** [andialbrecht/sqlparse#458]
```
statement = "select * from a;\n"
sqlparse.format(statement, reindent_aligned=True)
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/sqlparse/__init__.py", line 60, in format
    return u''.join(stack.run(sql, encoding))
  File "/Library/Python/2.7/site-packages/sqlparse/engine/filter_stack.py", line 39, in run
    filter_.process(stmt)
  File "/Library/Python/2.7/site-packages/sqlparse/filters/aligned_indent.py", line 128, in process
    self._process(stmt)
  File "/Library/Python/2.7/site-packages/sqlparse/filters/aligned_indent.py", line 125, in _process
    func(tlist)
  File "/Library/Python/2.7/site-packages/sqlparse/filters/aligned_indent.py", line 41, in _process_statement
    if tlist.tokens[0].is_whitespace and self.indent == 0:
IndexError: list index out of range

**Comment by andialbrecht** [comment]
Reopening this issue since the error is still reproducable :)

**Comment by sparklxb** [comment]
@andialbrecht Sorry, this error only exists in release packages and has been fixed in latest code. So, I closed the issue yesterday.

**Comment by andialbrecht** [comment]
@sparklxb, argh... sorry, my bad! I was lazy yesterday when testing this issue and just imported a released version of sqlparse in the virtual environment I was just working in :)

Thanks for clarification!
